# @package _global_

#### Model params #############################################################
model:
  name: agcrn
  hparams:
    hidden_size: 64
    emb_size: 10
    n_layers: 1

mask_as_exog: True