# @package _global_

#### Model params #############################################################
model:
  name: grud
  hparams:
    hidden_size: 64
    ff_size: 128
    ff_layers: 1
    n_layers: 2
    cat_states_layers: True
    fc: False
    activation: 'relu'
    imputation_loss: ${imputation_loss}

imputation_loss: False