# @package _global_

#### Model params #############################################################
model:
  name: gwnet
  hparams:
    hidden_size: 32
    ff_size: 256
    n_layers: 8
    temporal_kernel_size: 2
    spatial_kernel_size: 2
    learned_adjacency: True
    emb_size: 10
    dilation: 2
    dilation_mod: 2
    norm: batch
    dropout: 0.3
  receptive_field: 13

dataset:
  connectivity:
    layout: csr

mask_as_exog: True
