# @package _global_

#### Model params #############################################################
model:
  name: tts_amp
  hparams:
    hidden_size: 64  # 64, 32
    emb_size: 32  # 32, 16
    add_embedding_before: ['encoding', 'decoding']
    use_local_weights: null # ['encoder', 'decoder']
    time_layers: 1
    graph_layers: 4  # 2, 4
    activation: 'elu'

dataset:
  connectivity:
    layout: edge_index

mask_as_exog: True

