# @package _global_

defaults:
  - mso
  - _self_

#### Dataset params ###########################################################
dataset:
  name: mso_point
  hparams:
    p_fault: 0
    propagate_mask: False 